Feature/prework
anastasiya-charnahayeva/js-practice pull request #1
Opened 2024-04-25 07:32 UTC by anastasiya-charnahayeva

https://innowise-group.atlassian.net/browse/JST-1164

2024-04-29 16:04 UTC, AliaksandrInnowise requested changes

2024-04-29 16:04 UTC, ghost commented on index.html
> +           h1, h2 {
It's better to use class selectors to prevent applying styles to unexpected elements during further development

2024-04-29 16:04 UTC, ghost commented on index.html
> +
Something's wrong with empty spaces. It is nice to have a linter set up to handle this stuff. Usually, empty lines are limited to 2 in a row

2024-04-29 16:04 UTC, ghost commented on index.html
> + </div>
Same with indents for tags, it's nice to have them aligned with the level of nesting

2024-04-29 16:04 UTC, ghost commented on main.js
> +   const res = await fetch('https://jsonplaceholder.typicode.com/users')
The Promise in combination with async/await is redundant here, consider using either one of them in most of scenarios

2024-04-29 16:04 UTC, ghost commented on main.js
> +               option.innerText = `${user.name}`;
No need in string interpolation there, just assign the value `option.innerText = user.name`

2024-04-29 16:04 UTC, ghost commented on main.js
> +        createdDate = createdDate.setMonth(createdDate.getMonth() -  Math.floor(Math.random()*10));
What is random addition for?

2024-04-29 16:04 UTC, ghost commented on main.js
> +let v_height = 400;
If it is a constant better to define it notly only as a const, but with an uppercase constant, like `DEFAULT_VIEWPORT_HEIGHT`

2024-04-29 16:04 UTC, ghost commented on main.js
> +   polyline_y.setAttribute('style', 'stroke: black; stroke-width: 2');
It is very nice practice to move this kind of an inline string into the constant variables like `POLYLINE_STROKE_WIDTH = 'stroke-width: 2'` so it is easier to change them without diggin deep in the code

2024-04-29 16:04 UTC, ghost commented on main.js
> +    x_coor += 60;
Inline numbers like this are useful to be stored in a variable with a corresponding name, something like `X_AXIS_STEP`

2024-04-29 16:04 UTC, ghost commented on main.js
> +    for (var k in attrs)
Var 👀 k (poor naming) 👀

2024-04-29 16:04 UTC, ghost commented on main.js
> +        let total = percentagePostsPerUser.reduce(function (accu, that) { return that + accu; }, 0);
Why not arrow function for reduce callback? 👀 (both valid, just paying attention to alternatives)

2024-04-29 16:04 UTC, ghost commented on main.js
> +        let radius = v_height / 2 - strokeWidth / 2;
Nice that you try to store values inside variables, much easier to read 👍

2024-04-29 16:04 UTC, ghost commented on main.js
> +       let filteredUsers = selectedUsers.length !== users.length ? users.filter(user => selectedUsers.includes(user.id.toString())) : users;
It seems like you can remove the condition and just filter in any case without consequences.

2024-04-29 16:04 UTC, ghost commented on main.js
> +
Empty spaces!

2024-04-29 18:53 UTC, anastasiya-charnahayeva commented on index.html
> + </div>
+

2024-04-29 18:54 UTC, anastasiya-charnahayeva commented on index.html
> +
remember for future

2024-04-29 18:55 UTC, anastasiya-charnahayeva commented on main.js
> +
+

2024-04-29 19:11 UTC, anastasiya-charnahayeva commented on main.js
> +    x_coor += 60;
gotcha

2024-04-29 19:13 UTC, anastasiya-charnahayeva commented on main.js
> +   polyline_y.setAttribute('style', 'stroke: black; stroke-width: 2');
ok

2024-04-29 19:14 UTC, anastasiya-charnahayeva commented on main.js
> +let v_height = 400;
done.

2024-04-29 19:19 UTC, anastasiya-charnahayeva commented on main.js
> +        createdDate = createdDate.setMonth(createdDate.getMonth() -  Math.floor(Math.random()*10));
With a random function we created the dates that were before the current moment to show more real statistic

2024-04-29 19:21 UTC, anastasiya-charnahayeva commented on main.js
> +               option.innerText = `${user.name}`;
+

2024-04-29 19:45 UTC, anastasiya-charnahayeva commented on main.js
> +   const res = await fetch('https://jsonplaceholder.typicode.com/users')
it works. yep, thx

2024-04-29 19:48 UTC, anastasiya-charnahayeva commented on main.js
> +    for (var k in attrs)
^_^done

2024-04-29 19:48 UTC, anastasiya-charnahayeva commented on main.js
> +        let total = percentagePostsPerUser.reduce(function (accu, that) { return that + accu; }, 0);
okay)

2024-04-30 13:54 UTC, ghost approved these changes

2024-04-30 21:27 UTC, merged